-- COUPON TABLE 데이터 INSERT
SELECT *
FROM COUPON;

DESC COUPON;

DROP SEQUENCE c_num_seq;
CREATE SEQUENCE c_num_seq
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999999
    NOCYCLE
;

INSERT INTO COUPON
VALUES(c_num_seq.NEXTVAL, 62, '신규 회원가입 축하', 1, 50, 1);

COMMIT;