ALTER TABLE TICKET
	DROP
		CONSTRAINT FK_MOVIE_TO_TICKET
		CASCADE;

ALTER TABLE REVIEW
	DROP
		CONSTRAINT FK_MOVIE_TO_REVIEW
		CASCADE;

ALTER TABLE IMAGE
	DROP
		CONSTRAINT FK_MOVIE_TO_IMAGE
		CASCADE;

ALTER TABLE MOVIE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE FAQ
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE Member
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE TICKET
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE REVIEW
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE COUPON
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE IMAGE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_MOVIE;

DROP INDEX PK_FAQ;

DROP INDEX PK_Member;

DROP INDEX PK_TICKET;

DROP INDEX PK_REVIEW;

DROP INDEX PK_COUPON;

DROP INDEX PK_IMAGE;

/* 영화 */
DROP TABLE MOVIE 
	CASCADE CONSTRAINTS;

/* 게시판(문의) */
DROP TABLE FAQ 
	CASCADE CONSTRAINTS;

/* 회원 */
DROP TABLE Member 
	CASCADE CONSTRAINTS;

/* 결제내역 */
DROP TABLE TICKET 
	CASCADE CONSTRAINTS;

/* 상영정보 */
DROP TABLE MOVIE_INFO 
	CASCADE CONSTRAINTS;

/* 게시판(리뷰) */
DROP TABLE REVIEW 
	CASCADE CONSTRAINTS;

/* 쿠폰 */
DROP TABLE COUPON 
	CASCADE CONSTRAINTS;

/* 이미지 */
DROP TABLE IMAGE 
	CASCADE CONSTRAINTS;

/* 영화 */
CREATE TABLE MOVIE (
	MV_NUM NUMBER(9) NOT NULL, /* 영화번호 */
	MV_TITLE VARCHAR2(100) NOT NULL, /* 제목 */
	MV_DIRECTOR VARCHAR2(100) NOT NULL, /* 감독 */
	MV_ACTOR VARCHAR2(500) NOT NULL, /* 배우 */
	MV_GENRE VARCHAR2(100) NOT NULL, /* 장르 */
	MV_RELEASED DATE NOT NULL, /* 개봉일 */
	MV_AGELIMIT NUMBER(2) NOT NULL, /* 연령제한 */
	MV_SUMMARY VARCHAR2(4000) NOT NULL, /* 줄거리 */
	MV_NATION NUMBER(1) NOT NULL, /* 국가 */
	MV_TIME NUMBER(3) NOT NULL, /* 런닝타임 */
	MV_ON NUMBER(1) NOT NULL /* 상영여부 */
);

COMMENT ON TABLE MOVIE IS '영화';

COMMENT ON COLUMN MOVIE.MV_NUM IS '영화번호';

COMMENT ON COLUMN MOVIE.MV_TITLE IS '제목';

COMMENT ON COLUMN MOVIE.MV_DIRECTOR IS '감독';

COMMENT ON COLUMN MOVIE.MV_ACTOR IS '배우';

COMMENT ON COLUMN MOVIE.MV_GENRE IS '장르';

COMMENT ON COLUMN MOVIE.MV_RELEASED IS '개봉일';

COMMENT ON COLUMN MOVIE.MV_AGELIMIT IS '1,12,15,19';

COMMENT ON COLUMN MOVIE.MV_SUMMARY IS '줄거리';

COMMENT ON COLUMN MOVIE.MV_NATION IS '국내영화 1, 해외영화 2';

COMMENT ON COLUMN MOVIE.MV_TIME IS '런닝타임';

COMMENT ON COLUMN MOVIE.MV_ON IS '상영종료 0, 상영중 1, 상영예정 2';

CREATE UNIQUE INDEX PK_MOVIE
	ON MOVIE (
		MV_NUM ASC
	);

ALTER TABLE MOVIE
	ADD
		CONSTRAINT PK_MOVIE
		PRIMARY KEY (
			MV_NUM
		);

/* 게시판(문의) */
CREATE TABLE FAQ (
	Q_NUM NUMBER(7) NOT NULL, /* 게시판순번 */
	Q_KIND NUMBER(1) NOT NULL, /* 구분 */
	Q_TITLE VARCHAR2(100) NOT NULL, /* 제목 */
	Q_CONTENTS VARCHAR2(1000) NOT NULL, /* 내용 */
	Q_DATE DATE NOT NULL /* 작성일 */
);

COMMENT ON TABLE FAQ IS '게시판(문의)';

COMMENT ON COLUMN FAQ.Q_NUM IS '게시판순번';

COMMENT ON COLUMN FAQ.Q_KIND IS '1이면 공지, 2이면 일반글';

COMMENT ON COLUMN FAQ.Q_TITLE IS '제목';

COMMENT ON COLUMN FAQ.Q_CONTENTS IS '내용';

COMMENT ON COLUMN FAQ.Q_DATE IS '작성일';

CREATE UNIQUE INDEX PK_FAQ
	ON FAQ (
		Q_NUM ASC
	);

ALTER TABLE FAQ
	ADD
		CONSTRAINT PK_FAQ
		PRIMARY KEY (
			Q_NUM
		);
        
/* 회원 */
CREATE TABLE Member (
	MB_NUM NUMBER(7) NOT NULL, /* 회원번호 */
    MB_EMAIL VARCHAR2(200) UNIQUE NOT NULL, /*이메일*/
	MB_NAME VARCHAR2(100) NOT NULL, /* 이름 */
	MB_TEL VARCHAR2(20), /* 전화번호 */
	MB_BIRTH DATE NOT NULL, /* 생년월일 */
	MB_NICKNAME VARCHAR2(100), /* 닉네임 */
	MB_GRADE NUMBER(1) NOT NULL, /* 회원등급 */
	MB_POINT NUMBER(6) NOT NULL /* 포인트 */
);

COMMENT ON TABLE Member IS '회원';

COMMENT ON COLUMN Member.MB_NUM IS '회원번호';

COMMENT ON COLUMN Member.MB_EMAIL IS '이메일';

COMMENT ON COLUMN Member.MB_NAME IS '이름';

COMMENT ON COLUMN Member.MB_TEL IS '전화번호';

COMMENT ON COLUMN Member.MB_BIRTH IS '생년월일';

COMMENT ON COLUMN Member.MB_NICKNAME IS '닉네임';

COMMENT ON COLUMN Member.MB_GRADE IS '일반 1, 우수회원 2, VIP 3, VVIP 4';

COMMENT ON COLUMN Member.MB_POINT IS '포인트';

CREATE UNIQUE INDEX PK_Member
	ON Member (
		MB_NUM ASC
	);

ALTER TABLE Member
	ADD
		CONSTRAINT PK_Member
		PRIMARY KEY (
			MB_NUM
		);

/* 결제내역 */
CREATE TABLE TICKET (
	T_NUM VARCHAR2(100) NOT NULL, /* 결제번호 */
	MB_NUM NUMBER(7) NOT NULL, /* 회원번호 */
	T_PRICE NUMBER(6) NOT NULL, /* 결제금액 */
	T_MEANS NUMBER(1) NOT NULL, /* 결제수단 */
	T_TIME DATE NOT NULL, /* 결제일시 */
	T_STATUS NUMBER(1) NOT NULL, /* 결제상태 */
	MV_NUM NUMBER(9) NOT NULL /* 영화번호 */
);

COMMENT ON TABLE TICKET IS '결제내역';

COMMENT ON COLUMN TICKET.T_NUM IS '결제번호';

COMMENT ON COLUMN TICKET.MB_NUM IS '회원번호';

COMMENT ON COLUMN TICKET.T_PRICE IS '결제금액';

COMMENT ON COLUMN TICKET.T_MEANS IS '카드면 1, 카카오페이면 2';

COMMENT ON COLUMN TICKET.T_TIME IS '상영시간';

COMMENT ON COLUMN TICKET.T_STATUS IS '취소 0, 결제완료 1';

COMMENT ON COLUMN TICKET.MV_NUM IS '영화번호';

CREATE UNIQUE INDEX PK_TICKET
	ON TICKET (
		T_NUM ASC
	);

ALTER TABLE TICKET
	ADD
		CONSTRAINT PK_TICKET
		PRIMARY KEY (
			T_NUM
		);

/* 상영정보 */
CREATE TABLE MOVIE_INFO (
	MV_NUM NUMBER(9) NOT NULL, /* 영화번호 */
	MI_TIME DATE NOT NULL, /* 상영시간 */
	MI_QUALITY NUMBER(4) NOT NULL, /* 화질 */
	MI_VIDEO VARCHAR2(2083 CHAR) NOT NULL /* 동영상링크 */
);

COMMENT ON TABLE MOVIE_INFO IS '상영정보';

COMMENT ON COLUMN MOVIE_INFO.MV_NUM IS '영화번호';

COMMENT ON COLUMN MOVIE_INFO.MI_TIME IS '상영시간';

COMMENT ON COLUMN MOVIE_INFO.MI_QUALITY IS '720/1080/2160';

COMMENT ON COLUMN MOVIE_INFO.MI_VIDEO IS '유튜브 동영상 링크';

/* 게시판(리뷰) */
CREATE TABLE REVIEW (
	R_NUM NUMBER(8) NOT NULL, /* 리뷰순번 */
	R_RATING NUMBER(1) NOT NULL, /* 별점 */
	R_REVIEW VARCHAR2(500), /* 한줄평 */
	MB_NICKNAME VARCHAR2(100) NOT NULL, /* 작성자닉네임 */
	MV_NUM NUMBER(9) NOT NULL /* 영화번호 */
);

COMMENT ON TABLE REVIEW IS '게시판(리뷰)';

COMMENT ON COLUMN REVIEW.R_NUM IS '리뷰순번';

COMMENT ON COLUMN REVIEW.R_RATING IS '별점';

COMMENT ON COLUMN REVIEW.R_REVIEW IS '한줄평';

COMMENT ON COLUMN REVIEW.MV_NUM IS '영화번호';

CREATE UNIQUE INDEX PK_REVIEW
	ON REVIEW (
		R_NUM ASC
	);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT PK_REVIEW
		PRIMARY KEY (
			R_NUM
		);

/* 쿠폰 */
CREATE TABLE COUPON (
	C_NUM NUMBER(7) NOT NULL, /* 쿠폰번호 */
	MB_NUM NUMBER(7) NOT NULL, /* 회원번호 */
	C_NAME VARCHAR2(200) NOT NULL, /* 쿠폰이름 */
	C_TARGET NUMBER(2) NOT NULL, /* 적용대상 */
	C_RATIO NUMBER(2) NOT NULL, /* 할인율 */
	C_KIND NUMBER(1) /* 사용구분 */
);

COMMENT ON TABLE COUPON IS '쿠폰';

COMMENT ON COLUMN COUPON.C_NUM IS '쿠폰번호';

COMMENT ON COLUMN COUPON.MB_NUM IS '회원번호';

COMMENT ON COLUMN COUPON.C_NAME IS '쿠폰이름';

COMMENT ON COLUMN COUPON.C_TARGET IS '1이면 생일쿠폰, 2이면 가입축하기념';

COMMENT ON COLUMN COUPON.C_RATIO IS '할인율 %값';

COMMENT ON COLUMN COUPON.C_KIND IS '0이면 사용완료 1이면 미사용';

CREATE UNIQUE INDEX PK_COUPON
	ON COUPON (
		C_NUM ASC
	);

ALTER TABLE COUPON
	ADD
		CONSTRAINT PK_COUPON
		PRIMARY KEY (
			C_NUM
		);

/* 이미지 */
CREATE TABLE IMAGE (
	MV_NUM NUMBER(9) NOT NULL, /* 영화번호 */
	MV_SEQ NUMBER(2) NOT NULL, /* 영화순번 */
	IM_ROUTE VARCHAR2(256 CHAR) NOT NULL /* 파일경로 */
);

COMMENT ON TABLE IMAGE IS '이미지';

COMMENT ON COLUMN IMAGE.MV_NUM IS '영화번호';

COMMENT ON COLUMN IMAGE.MV_SEQ IS '영화순번';

COMMENT ON COLUMN IMAGE.IM_ROUTE IS '파일경로';

CREATE UNIQUE INDEX PK_IMAGE
	ON IMAGE (
		MV_NUM ASC,
		MV_SEQ ASC
	);

ALTER TABLE IMAGE
	ADD
		CONSTRAINT PK_IMAGE
		PRIMARY KEY (
			MV_NUM,
			MV_SEQ
		);

ALTER TABLE TICKET
	ADD
		CONSTRAINT FK_MOVIE_TO_TICKET
		FOREIGN KEY (
			MV_NUM
		)
		REFERENCES MOVIE (
			MV_NUM
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_MOVIE_TO_REVIEW
		FOREIGN KEY (
			MV_NUM
		)
		REFERENCES MOVIE (
			MV_NUM
		);

ALTER TABLE IMAGE
	ADD
		CONSTRAINT FK_MOVIE_TO_IMAGE
		FOREIGN KEY (
			MV_NUM
		)
		REFERENCES MOVIE (
			MV_NUM
		);

DROP SEQUENCE column_seq;
CREATE SEQUENCE column_seq
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 99999999
    NOCYCLE
;